### ISSUE TITLE
Error (I think converting html to epub?) I'm not sure what this is about

### ISSUE THREAD

**Issue by ChrisP4** [transpect/pdf2fxl#2]
I ran ./pdf2fxl nameofmyfile.pdf -e
It's extracting pages and creating a folder which has the page's html files. But then I get this:

    PDF extraction finished  
    Convert single page HTML to wrapped HTML  
    ERROR: http://transpect.github.io/../index.html:1:107:Not a pipeline or library: html  
    ERROR: err:XS0044:Unexpected step name: tr:simple-progress-msg  
    ERROR: It is a static error if any element in the XProc namespace or any step has element children  
    other than those specified for it by this specification. In particular, the presence of atomic steps for  
    which there is no visible declaration may raise this error.

**Comment by gimsieke** [comment]
This is due to a stupid bug that emerged by itself at some point in time. 

Background: We use XML catalogs to include files from libraries by abstract URLs such as `http://transpect.io/somelib/someXslt.xsl`. These URLs will be resolved to local `file:` URLs by means of the catalog. In transpect pipelines, there’s often a configuration cascade where the XProc processor tries to include files from different locations, the most specific configuration first. 
Previously, we didn’t resolve the abstract URLs where we searched for configuration files prior to retrieving the files. If there was no configuration at the expected location, the HTTP request that tried to retrieve the file would fail and processor would just check the next-specific location.

Background 2: We are hosting Github pages that pertain to transpect on http://transpect.io

Previously, when the processor tried to access a resource with the abstract, unresolved URI under http://transpect.io, Github pages would return an HTML file that was not well-formed XML. Then they changed something, and suddenly we received a well-formed XHTML page when requesting a non-existent transpect resource. 

We then changed the configuration cascade loading so that the abstract URLs would be resolved to local `file:` URLs prior to trying to load the corresponding resources. Thus we avoided Github delivering an XHTML page instead of an error for non-existing resources.

Sounds complicated? That’s what we thought, too. You can imagine it took us some time to identify the root cause of the problem and to come up with a solution. 

Unfortunately, the solution has to be applied to existing projects. They just cease to run after this change by Github. And that’s what @mkraetke needs to do occasionally with this project. 
Then github changed

**Comment by mkraetke** [comment]
@ChrisP4 I've made some changes and updated the modules to the latest version. I also rewrote the README, so there should be no Git submodule issues if you follow the instructions.

**Comment by ChrisP4** [comment]
Thank you for the superfast attention and your time!

I tried with the updated version and it seems like it creates an .epub file. However I tried two different .pdf files and while I get no errors ([info] PDF extraction finished), upon trying to open the .epub files (with calibre viewer) I get the following error:

calibre, version 3.27.1
ERROR: Could not open e-book: Failed to read book, /home/myname/pdf2fxl/filename.epub click "Show Details" for more information

Traceback (most recent call last):
  File "site-packages/calibre/utils/ipc/simple_worker.py", line 289, in main
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 65, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 267, in convert
  File "site-packages/calibre/utils/localunzip.py", line 231, in extractall
  File "site-packages/calibre/utils/localunzip.py", line 218, in _extractall
ValueError: Not a ZIP file

**Comment by mkraetke** [comment]
OK, this seems a bit odd to me. Looks like some Phython scripts hung up. Would you please try to open the EPUB with Bluefire Reader or Microsoft Edge (seriously a very decent EPUB reader)? I have to admit that I didn't work with Calibre, but I'll install it and report back to you.

**Comment by mkraetke** [comment]
My sample file works well with Calibre. However, you can send me your PDF via E-Mail. Please refer to [this site for my contact details](https://www.le-tex.de/en/MartinKraetke.html).

**Comment by ChrisP4** [comment]
@mkraetke I can't try Microsoft Edge (i'm on linux), I'm sending you one of the two .pdf's I tried.
Thank you so very much for your time and patience!

**Comment by ChrisP4** [comment]
Did you get my email all those days ago? Were you successful in converting the .PDF?

**Comment by mayercn** [comment]
Is it possible to create the epub file by hand using the remaining files in the *.tmp folder? I am really not too much into the epub format...

**Comment by mayercn** [comment]
BTW @ChrisP4: After searching half the night, I have found a great alternative: https://www.pdfmate.com. It looks a bit pushy but the free desktop program did a great job converting my large PDF. Beautiful output.

**Comment by mkraetke** [comment]
@mayercn please just provide me your input file. I cannot solve this issue without having any chance to reproduce it.

**Comment by ChrisP4** [comment]
@mayercn thanks, but I only have linux :(

**Comment by SundeepPidugu** [comment]
> OK, this seems a bit odd to me. Looks like some Phython scripts hung up. Would you please try to open the EPUB with Bluefire Reader or Microsoft Edge (seriously a very decent EPUB reader)? I have to admit that I don't work with Calibre, but I'll install it and report back to you.

Any update on this ? even iam unable to open the file and reported an issue.

**Comment by mkraetke** [comment]
@SundeepPidugu: Please send me your PDF and EPUB via email. Otherwise I'm unable to reproduce the issue.

**Comment by SundeepPidugu** [comment]
@mkraetke Sent you the output files via email at : [martin.kraetke@le-tex.de](mailto:martin.kraetke@le-tex.de)
